bug_tracker/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', user_views.LoginSuccessView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), 
        name='password_reset'),
    path('password-reset/done', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('password-reset-complete', 
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
        name='password_reset_complete'),
    path('', include('pybug.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybug/urls.py
from django.urls import path, include
from .views import (
    ProjectlistView,
    ProjectCreateView,
    TicketListView,
    TicketCreateView, 
    TicketUpdateView,
    TicketDeleteView,
    UserTicketListView,
    TicketAPIView,
    TicketDetailAPIView,
    ProjectAPIView,
    ProjectDetailAPIView,
)
from . import views


app_urlpatterns = [
    path('', ProjectlistView.as_view(), name='pybug-projects'),
    path('user/<str:username>/', UserTicketListView.as_view(), name='user-tickets'),
    path('project/<str:key>/tickets/<int:pk>/', TicketListView.as_view(), name='project-detail'),
    path('project/new/', ProjectCreateView.as_view(), name='project-create'),
    path('ticket/new/', TicketCreateView.as_view(), name='ticket-create'),
    path('ticket/<int:pk>/update/', TicketUpdateView.as_view(), name='ticket-update'),
    path('ticket/<int:pk>/delete/', TicketDeleteView.as_view(), name='ticket-delete'),
]


api_urlpatterns = [
    path('api/tickets/', TicketAPIView.as_view()),
    path('api/ticket/<int:pk>', TicketDetailAPIView.as_view()),
    path('api/projects/', ProjectAPIView.as_view()),
    path('api/project/<int:pk>', ProjectDetailAPIView.as_view()),
]


urlpatterns = [
    path('', include(app_urlpatterns)),
    path('', include(api_urlpatterns)),
]

pybug/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from django.urls import reverse
from datetime import datetime, timedelta


class Project(models.Model):

    name = models.CharField(max_length=100)
    key = models.CharField(max_length=10,
                           unique=True)
    description = models.TextField()
    lead = models.ForeignKey(User,
                             null=True,
                             on_delete=models.SET_NULL,
                             related_name='projects')
    tech = models.CharField(max_length=50, null=True)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pybug-projects')


class Priority(models.Model):

    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Ticket(models.Model):

    title = models.CharField(max_length=100)
    description = models.TextField(null=True,
                                   blank=True)
    date_reported = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)
    reporter = models.ForeignKey(User,
                                 null=True,
                                 on_delete=models.SET_NULL,
                                 related_name='reported_tickets')
    assignee = models.ForeignKey(User,
                                 blank=True,
                                 null=True,
                                 on_delete=models.SET_NULL,
                                 related_name='assigned_tickets')
    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                related_name='project_tickets')
    priority = models.ForeignKey(Priority,
                                 null=True,
                                 default=1,
                                 on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('project-detail', kwargs={'key': self.project.key, 'pk': self.pk})


class Comment(models.Model):

    ticket = models.ForeignKey(Ticket,
                               on_delete=models.CASCADE,
                               related_name='comments')
    user = models.ForeignKey(User,
                             null=True,
                             on_delete=models.SET_NULL)
    content = models.TextField(max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)

    def get_human_time(self):
        time = timezone.now()
        minutes_diff = (time - self.timestamp).total_seconds() / 60.0
        if minutes_diff < 60:
            return str(int(minutes_diff)) + " minute(s) ago"
        elif self.timestamp.day == time.day:
            return str(time.hour - self.timestamp.hour) + " hour(s) ago"
        elif self.timestamp.month == time.month:
            return str(time.day - self.timestamp.day) + " day(s) ago"
        elif self.timestamp.year == time.year:
            return str(time.month - self.timestamp.month) + " month(s) ago"
        else:
            return self.timestamp

    def __str__(self):
        return f'Comment({self.id}, {self.user.username})'

pybug/forms.py
from django import forms
from .models import Comment, Ticket


class TicketForm(forms.ModelForm):

    title = forms.CharField(label=False, widget=forms.TextInput(
        attrs={
            'rows': 1,
            'style': 'font-size: xx-large; border: none;',            
            }
    ))

    description = forms.CharField(label=False, widget=forms.Textarea(
        attrs={
            'placeholder': 'Add a description...',
            'rows': 4,
            'style': 'border: none;',     
            }
    ))

    class Meta:
        model = Ticket
        fields = ['title', 'description', 'reporter', 'assignee', 'priority']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        return super().save(commit=commit)


class CommentForm(forms.Form):

    comment_content = forms.CharField(label=False, widget=forms.Textarea(
        attrs={
            'placeholder': 'Add a comment...',
            'rows': 1,
            'verbose_name': "",
            }
    ))

pybug/views/api_views.py
from django.shortcuts import render
from django.http import HttpResponse
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from pybug.models import Ticket, Project
from pybug.serializers import TicketSerializer, ProjectSerializer


class AuthenticatedAPIView(APIView):

    authentication_classes = [SessionAuthentication, BasicAuthentication, TokenAuthentication]
    permission_classes = [IsAuthenticated]    


class TicketAPIView(AuthenticatedAPIView):

    def get(self, request):
        tickets = Ticket.objects.all()
        serializer = TicketSerializer(tickets, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = TicketSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.data, status=status.HTTP_400_BAD_REQUEST)


class TicketDetailAPIView(AuthenticatedAPIView):

    def get_object(self, pk):
        try:
            return Ticket.objects.get(pk=pk)
        except Ticket.DoesNotExist:
            return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    def get(self, request, pk):
        ticket = self.get_object(pk)
        serializer = TicketSerializer(ticket)
        return Response(serializer.data)

    def put(self, request, pk):
        ticket = self.get_object(pk)
        serializer = TicketSerializer(ticket, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        ticket = self.get_object(pk)
        ticket.delete()
        return HttpResponse(status=status.HTTP_204_NO_CONTENT)


class ProjectAPIView(AuthenticatedAPIView):

    def get(self, request):
        projects = Project.objects.all()
        serializer = ProjectSerializer(projects, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = ProjectSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.data, status=status.HTTP_400_BAD_REQUEST)


class ProjectDetailAPIView(AuthenticatedAPIView):

    def get_object(self, pk):
        try:
            return Project.objects.get(pk=pk)
        except Project.DoesNotExist:
            return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    def get(self, request, pk):
        project = self.get_object(pk)
        serializer = ProjectSerializer(project)
        return Response(serializer.data)

    def put(self, request, pk):
        project = self.get_object(pk)
        serializer = ProjectSerializer(project, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        project = self.get_object(pk)
        project.delete()
        return HttpResponse(status=status.HTTP_204_NO_CONTENT)

pybug/views/app_views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import FormMixin
from users.models import User
from django.core.paginator import Paginator
from django.views.generic import (
    ListView, 
    DetailView, 
    CreateView, 
    UpdateView, 
    DeleteView
)
from pybug.models import Ticket, Project, Comment
from pybug.forms import TicketForm, CommentForm


class ProjectlistView(ListView):
    model = Project
    template_name = 'pybug/projects.html'
    context_object_name = 'projects'
    ordering = ['-date_created']
    paginate_by = 10


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['name', 'key', 'tech', 'description', 'lead']
    

class TicketListView(FormMixin, ListView):
    model = Ticket
    template_name = 'pybug/ticket_detail.html'
    context_object_name = 'tickets'
    paginate_by = 5
    form_class = TicketForm

    def get_form_kwargs(self):
        kwargs = {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'instance': self.get_object()
        }

        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def get_success_url(self):
        ticket = self.get_object()
        return ticket.get_absolute_url()

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        ticket = self.get_object()
        ticket_form = self.get_form()

        if 'comment_content' in request.POST:
            comment_content = request.POST.get('comment_content')
            if comment_content != '':
                comment = Comment.objects.create(ticket=ticket, 
                                                    user=request.user, 
                                                    content=comment_content)
                comment.save()
        elif ticket_form.is_valid():
            ticket_form.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_object(self):
        pk = self.kwargs.get('pk')
        if pk == 0: return None
        return get_object_or_404(Ticket, pk=pk)

    def get_queryset(self):
        project = get_object_or_404(Project, key=self.kwargs.get('key'))
        return Ticket.objects.filter(project=project).order_by('-date_reported')

    def get_context_data(self, **kwargs):
        project = get_object_or_404(Project, key=self.kwargs.get('key'))
        display_ticket = self.get_object()
        comments = Comment.objects.filter(ticket=display_ticket).order_by('-timestamp')
        comment_form = CommentForm()

        context = super().get_context_data(**kwargs)
        context['display_ticket'] = display_ticket
        context['project'] = project
        context['comments'] = comments
        context['comment_form'] = comment_form

        return context


class UserTicketListView(ListView):
    model = Ticket
    template_name = 'pybug/user_tickets.html'
    context_object_name = 'tickets'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Ticket.objects.filter(reporter=user).order_by('-date_reported')


class TicketCreateView(LoginRequiredMixin, CreateView):
    model = Ticket
    fields = ['project', 'title', 'description', 'assignee']

    def get_initial(self):
        initial = super().get_initial()
        initial['project'] = self.request.GET.get('project')
        return initial

    def form_valid(self, form):
        form.instance.reporter = self.request.user
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UpdateView):
    model = Ticket
    fields = ['title', 'description', 'assignee', 'priority']

    def form_valid(self, form):
        form.instance.reporter = self.request.user
        return super().form_valid(form)


class TicketDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Ticket
    success_url = '/'

    def test_func(self):
        ticket = self.get_object()
        return self.request.user == ticket.reporter


def about(request):
    return render(request, template_name='pybug/about.html', context={'title': 'About'})

pybug/templates/pybug/base.html
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'pybug/main.css' %}">

  {% if title %}
  <title>Bug_Tracker - {{ title }}</title>
  {% else %}
  <title>Bug_Tracker</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand mr-4" href="{% url 'pybug-projects' %}">Bug_Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'pybug-projects' %}">Projects</a>
            <a class="nav-item nav-link" href="{% url 'ticket-create' %}">New Ticket</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

  <main role="main" class="container-fluid">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

pybug/templates/pybug/project_form.html
{% extends 'pybug/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {% if object %}
                    <legend class="border-bottom mb-4">
                        Update Project
                    </legend>
                {% else %}
                    <legend class="border-bottom mb-4">
                        New Project
                    </legend>
                {% endif %}
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

pybug/templates/pybug/projects.html
{% extends 'pybug/base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-md-12 mb-3">
        <span style="float:left;">
            <h2>Projects</h2>
        </span>
        <span style="float:right;">
            <a type="button" class="btn btn-primary" href="{% url 'project-create' %}" role="button">New Project</a>
        </span>
    </div>
    <div class="col-md-12">
        <table class='table table-hover'>
            <thead>
                <tr>
                <th scope="col">Name</th>
                <th scope="col">Key</th>
                <th scope="col">Tech</th>
                <th scope="col">Date created</th>
                <th scope="col">Lead</th>
                </tr>
            </thead>
            <tbody>
                {% for project in projects %}
                    <tr class='clickable-row' data-href="{% url 'project-detail' project.key project.project_tickets.last.id|default:0 %}?page={{ page_obj.number }}">
                        <td>{{ project.name }}</td>
                        <td>{{ project.key }}</td>
                        <td>{{ project.tech }}</td>
                        <td>{{ project.date_created|date:"F d, Y" }}</td>
                        <td>{{ project.lead.get_full_name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>

        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn-sm btn-outline-info mb-4" href="?page=1">First</a>
                ...
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn-sm btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                    <a class="btn-sm btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                ...
                <a class="btn-sm btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        
        {% endif %}

        </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="{% static 'pybug/scripts.js' %}"></script>
<script>
    $('form :input').blur(function() {
        console.log($(this).closest('form'))
        $(this).closest('form').submit();
    });
</script>

{% endblock content %}

pybug/templates/pybug/ticket_confirm_delete.html
{% extends 'pybug/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Delete Ticket
                </legend>
                <h2>Are you sure you want to delete the ticket "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'project-detail' object.project.key object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

pybug/templates/pybug/ticket_detail.html
{% extends 'pybug/ticket_list.html' %}
{% load crispy_forms_field %}
{% load crispy_forms_tags %}
{% block ticket_detail %}
<div class="col-md-10">
    <div class="media content-section">
        <div class="media-body">
            <div class="article-metadata mb-3">
                <small class="text-muted">{{ display_ticket.date_reported|date:"F d, Y" }}</small>
                <div class="dropdown">
                    <svg onclick="actionMenu()" class="dropbtn" width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation">
                        <g fill="currentColor" fill-rule="evenodd">
                            <circle cx="5" cy="12" r="2"></circle>
                            <circle cx="12" cy="12" r="2"></circle>
                            <circle cx="19" cy="12" r="2"></circle>
                        </g>
                    </svg>
                    <div id="actionMenu" class="dropdown-content">
                        <a href="{% url 'ticket-update' display_ticket.id %}">Update</a>
                        {% if display_ticket.reporter == user %}
                            <a href="{% url 'ticket-delete' display_ticket.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div> 
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-9">
                        {{ form.title|as_crispy_field }}
                        <div class="col-md-12">
                            <div class="panel-heading mb-2">Description</div>
                            {{ form.description|as_crispy_field }}
                        </div>                                
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <br>
                            {% if display_ticket.reporter.username %}
                                {{ form.reporter|as_crispy_field }}
                            {% else %}
                                {{ form.reporter|as_crispy_field }}
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <br>
                            {% if display_ticket.assignee.username %}
                                {{ form.assignee|as_crispy_field }}
                            {% else %}
                                {{ form.assignee|as_crispy_field }}
                            {% endif %}
                        </div> 
                        <div class="mb-3">
                            <br>
                            {{ form.priority|as_crispy_field }}
                        </div> 
                    </div>
                </div>
            </form>
            <div class="row">                                
                <div class="col-md-9">
                    <br><hr>
                    <div class="row main-comment-section">
                        <div class="col-md-12 col-sm-12">
                            <div class="comment-wrapper">
                                <div class="panel panel-info">
                                    <div class="panel-heading mb-2">Comments</div><br>
                                    <div class="panel-body">
                                        <ul class="media-list">                            
                                        {% for comment in comments %}
                                            <li class="media">
                                                <div class="media pull-left">
                                                    <img class="rounded-circle account-img" src="{{ comment.user.profile.image.url }}">
                                                </div>
                                                <div class="media-body">
                                                    <strong class="text-success">{{ comment.user.get_full_name }}</strong>
                                                    <span class="text-muted pull-right">
                                                        <small class="text-muted">{{ comment.get_human_time }}</small>
                                                    </span>
                                                    <p>{{ comment.content }}</p>
                                                </div>
                                            </li>
                                        {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>    
                        </div>
                    </div>                                     
                    <form method="POST">
                        {% csrf_token %}
                        {{ comment_form.comment_content|as_crispy_field }}
                        <br><input type="submit" name="action" value="Post" class="btn btn-info pull-right">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock ticket_detail %}

pybug/templates/pybug/ticket_form.html
{% extends 'pybug/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {% if object %}
                    <legend class="border-bottom mb-4">
                        Update Ticket
                    </legend>
                {% else %}
                    <legend class="border-bottom mb-4">
                        New Ticket
                    </legend>
                {% endif %}
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

pybug/templates/pybug/user_tickets.html
{% extends 'pybug/base.html' %}
{% block content %}
    <h1 class="mb-3">Tickets reported by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for ticket in tickets %}
        <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-tickets' ticket.reporter.username %}">{{ ticket.reporter.get_full_name }}</a>
                <small class="text-muted">{{ ticket.date_reported|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'project-detail' ticket.project.key ticket.id %}">{{ ticket.title }}</a></h2>
            <p class="article-content">{{ ticket.description }}</p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn-sm btn-outline-info mb-4" href="?page=1">First</a>
            ...
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn-sm btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                <a class="btn-sm btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            ...
            <a class="btn-sm btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}